spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/fitrscheduledb?useSSL=false&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  address: localhost
  port: 4973